# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'XCC_Agent_Design.ui'
#
# Created: Mon Sep 05 10:47:50 2016
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName(_fromUtf8("Dialog"))
        Dialog.resize(500, 300)
        Dialog.setMinimumSize(QtCore.QSize(500, 300))
        Dialog.setMaximumSize(QtCore.QSize(500, 300))
        font = QtGui.QFont()
        font.setKerning(True)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        Dialog.setFont(font)
        Dialog.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("XCC.ico")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setToolTip(_fromUtf8(""))
        Dialog.setWhatsThis(_fromUtf8(""))
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(6, 9, 491, 281))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setElideMode(QtCore.Qt.ElideMiddle)
        self.tabWidget.setUsesScrollButtons(True)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Status = QtGui.QWidget()
        self.Status.setObjectName(_fromUtf8("Status"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.Status)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(9, 19, 471, 141))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        spacerItem = QtGui.QSpacerItem(14, 14, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem, 6, 1, 1, 1)
        self.label_status_XCCWorkflowService = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_status_XCCWorkflowService.setText(_fromUtf8(""))
        self.label_status_XCCWorkflowService.setObjectName(_fromUtf8("label_status_XCCWorkflowService"))
        self.gridLayout_2.addWidget(self.label_status_XCCWorkflowService, 5, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_11.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_2.addWidget(self.label_11, 1, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(332, 20, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 6, 2, 1, 1)
        self.status_web = QtGui.QLabel(self.gridLayoutWidget_2)
        self.status_web.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Symbol"))
        self.status_web.setFont(font)
        self.status_web.setText(_fromUtf8(""))
        self.status_web.setAlignment(QtCore.Qt.AlignCenter)
        self.status_web.setMargin(-9)
        self.status_web.setObjectName(_fromUtf8("status_web"))
        self.gridLayout_2.addWidget(self.status_web, 0, 1, 1, 1)
        self.label_12 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_2.addWidget(self.label_12, 3, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_9.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_2.addWidget(self.label_9, 0, 0, 1, 1)
        self.status_XCCHotFolder = QtGui.QLabel(self.gridLayoutWidget_2)
        self.status_XCCHotFolder.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Symbol"))
        self.status_XCCHotFolder.setFont(font)
        self.status_XCCHotFolder.setText(_fromUtf8(""))
        self.status_XCCHotFolder.setAlignment(QtCore.Qt.AlignCenter)
        self.status_XCCHotFolder.setMargin(-9)
        self.status_XCCHotFolder.setObjectName(_fromUtf8("status_XCCHotFolder"))
        self.gridLayout_2.addWidget(self.status_XCCHotFolder, 3, 1, 1, 1)
        self.label_15 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_15.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 5, 0, 1, 1)
        self.status_XCCWorkflowService = QtGui.QLabel(self.gridLayoutWidget_2)
        self.status_XCCWorkflowService.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Symbol"))
        self.status_XCCWorkflowService.setFont(font)
        self.status_XCCWorkflowService.setText(_fromUtf8(""))
        self.status_XCCWorkflowService.setAlignment(QtCore.Qt.AlignCenter)
        self.status_XCCWorkflowService.setMargin(-9)
        self.status_XCCWorkflowService.setObjectName(_fromUtf8("status_XCCWorkflowService"))
        self.gridLayout_2.addWidget(self.status_XCCWorkflowService, 5, 1, 1, 1)
        self.label_status_web = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_status_web.setMaximumSize(QtCore.QSize(331, 16777215))
        self.label_status_web.setText(_fromUtf8(""))
        self.label_status_web.setObjectName(_fromUtf8("label_status_web"))
        self.gridLayout_2.addWidget(self.label_status_web, 0, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 6, 0, 1, 1)
        self.label_status_XCCService = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_status_XCCService.setText(_fromUtf8(""))
        self.label_status_XCCService.setObjectName(_fromUtf8("label_status_XCCService"))
        self.gridLayout_2.addWidget(self.label_status_XCCService, 1, 2, 1, 1)
        self.label_13 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_13.setMaximumSize(QtCore.QSize(300, 16777215))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_2.addWidget(self.label_13, 2, 0, 1, 1)
        self.label_status_XCCHotFolder = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_status_XCCHotFolder.setText(_fromUtf8(""))
        self.label_status_XCCHotFolder.setObjectName(_fromUtf8("label_status_XCCHotFolder"))
        self.gridLayout_2.addWidget(self.label_status_XCCHotFolder, 3, 2, 1, 1)
        self.status_XCCService = QtGui.QLabel(self.gridLayoutWidget_2)
        self.status_XCCService.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Symbol"))
        self.status_XCCService.setFont(font)
        self.status_XCCService.setText(_fromUtf8(""))
        self.status_XCCService.setAlignment(QtCore.Qt.AlignCenter)
        self.status_XCCService.setMargin(-9)
        self.status_XCCService.setObjectName(_fromUtf8("status_XCCService"))
        self.gridLayout_2.addWidget(self.status_XCCService, 1, 1, 1, 1)
        self.label_status_XCCResponseService = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_status_XCCResponseService.setText(_fromUtf8(""))
        self.label_status_XCCResponseService.setObjectName(_fromUtf8("label_status_XCCResponseService"))
        self.gridLayout_2.addWidget(self.label_status_XCCResponseService, 2, 2, 1, 1)
        self.status_XCCResponseService = QtGui.QLabel(self.gridLayoutWidget_2)
        self.status_XCCResponseService.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Symbol"))
        self.status_XCCResponseService.setFont(font)
        self.status_XCCResponseService.setText(_fromUtf8(""))
        self.status_XCCResponseService.setAlignment(QtCore.Qt.AlignCenter)
        self.status_XCCResponseService.setMargin(-9)
        self.status_XCCResponseService.setObjectName(_fromUtf8("status_XCCResponseService"))
        self.gridLayout_2.addWidget(self.status_XCCResponseService, 2, 1, 1, 1)
        self.label_14 = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_2.addWidget(self.label_14, 4, 0, 1, 1)
        self.status_XCCNearline_Spectro = QtGui.QLabel(self.gridLayoutWidget_2)
        self.status_XCCNearline_Spectro.setMaximumSize(QtCore.QSize(20, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Symbol"))
        self.status_XCCNearline_Spectro.setFont(font)
        self.status_XCCNearline_Spectro.setText(_fromUtf8(""))
        self.status_XCCNearline_Spectro.setAlignment(QtCore.Qt.AlignCenter)
        self.status_XCCNearline_Spectro.setMargin(-9)
        self.status_XCCNearline_Spectro.setObjectName(_fromUtf8("status_XCCNearline_Spectro"))
        self.gridLayout_2.addWidget(self.status_XCCNearline_Spectro, 4, 1, 1, 1)
        self.label_status_XCCNearline_Spectro = QtGui.QLabel(self.gridLayoutWidget_2)
        self.label_status_XCCNearline_Spectro.setText(_fromUtf8(""))
        self.label_status_XCCNearline_Spectro.setObjectName(_fromUtf8("label_status_XCCNearline_Spectro"))
        self.gridLayout_2.addWidget(self.label_status_XCCNearline_Spectro, 4, 2, 1, 1)
        self.pushButton_Refresh = QtGui.QPushButton(self.Status)
        self.pushButton_Refresh.setGeometry(QtCore.QRect(360, 200, 111, 23))
        self.pushButton_Refresh.setMaximumSize(QtCore.QSize(120, 16777215))
        self.pushButton_Refresh.setObjectName(_fromUtf8("pushButton_Refresh"))
        self.checkBox_RunBootUp = QtGui.QCheckBox(self.Status)
        self.checkBox_RunBootUp.setGeometry(QtCore.QRect(10, 200, 241, 17))
        self.checkBox_RunBootUp.setObjectName(_fromUtf8("checkBox_RunBootUp"))
        self.label_10 = QtGui.QLabel(self.Status)
        self.label_10.setGeometry(QtCore.QRect(10, 230, 41, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.Label_Version_Number = QtGui.QLabel(self.Status)
        self.Label_Version_Number.setGeometry(QtCore.QRect(50, 230, 91, 16))
        self.Label_Version_Number.setText(_fromUtf8(""))
        self.Label_Version_Number.setObjectName(_fromUtf8("Label_Version_Number"))
        self.pushButton_DownloadUpdate = QtGui.QPushButton(self.Status)
        self.pushButton_DownloadUpdate.setEnabled(False)
        self.pushButton_DownloadUpdate.setGeometry(QtCore.QRect(361, 230, 111, 23))
        self.pushButton_DownloadUpdate.setCheckable(False)
        self.pushButton_DownloadUpdate.setObjectName(_fromUtf8("pushButton_DownloadUpdate"))
        self.tabWidget.addTab(self.Status, _fromUtf8(""))
        self.User = QtGui.QWidget()
        self.User.setObjectName(_fromUtf8("User"))
        self.formLayoutWidget = QtGui.QWidget(self.User)
        self.formLayoutWidget.setGeometry(QtCore.QRect(9, 9, 291, 81))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label = QtGui.QLabel(self.formLayoutWidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEditEmail = QtGui.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setKerning(False)
        self.lineEditEmail.setFont(font)
        self.lineEditEmail.setObjectName(_fromUtf8("lineEditEmail"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditEmail)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineEditPassword = QtGui.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setKerning(True)
        self.lineEditPassword.setFont(font)
        self.lineEditPassword.setEchoMode(QtGui.QLineEdit.Password)
        self.lineEditPassword.setObjectName(_fromUtf8("lineEditPassword"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditPassword)
        self.pushButtonUser_Reset = QtGui.QPushButton(self.formLayoutWidget)
        self.pushButtonUser_Reset.setObjectName(_fromUtf8("pushButtonUser_Reset"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.pushButtonUser_Reset)
        self.pushButtonUser_Connect = QtGui.QPushButton(self.formLayoutWidget)
        self.pushButtonUser_Connect.setObjectName(_fromUtf8("pushButtonUser_Connect"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.pushButtonUser_Connect)
        self.label_Status = QtGui.QLabel(self.User)
        self.label_Status.setGeometry(QtCore.QRect(10, 100, 289, 71))
        self.label_Status.setText(_fromUtf8(""))
        self.label_Status.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label_Status.setObjectName(_fromUtf8("label_Status"))
        self.tabWidget.addTab(self.User, _fromUtf8(""))
        self.Proxy = QtGui.QWidget()
        self.Proxy.setObjectName(_fromUtf8("Proxy"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.Proxy)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 291, 102))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label_5 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_5)
        self.checkBoxProxy = QtGui.QCheckBox(self.formLayoutWidget_2)
        self.checkBoxProxy.setText(_fromUtf8(""))
        self.checkBoxProxy.setObjectName(_fromUtf8("checkBoxProxy"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.checkBoxProxy)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_3)
        self.lineEditProxy_Address = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEditProxy_Address.setEnabled(False)
        self.lineEditProxy_Address.setMaximumSize(QtCore.QSize(208, 16777215))
        font = QtGui.QFont()
        font.setKerning(True)
        self.lineEditProxy_Address.setFont(font)
        self.lineEditProxy_Address.setObjectName(_fromUtf8("lineEditProxy_Address"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditProxy_Address)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_4)
        self.lineEditProxy_Port = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEditProxy_Port.setEnabled(False)
        font = QtGui.QFont()
        font.setKerning(True)
        self.lineEditProxy_Port.setFont(font)
        self.lineEditProxy_Port.setObjectName(_fromUtf8("lineEditProxy_Port"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditProxy_Port)
        self.pushButtonProxy_Reset = QtGui.QPushButton(self.formLayoutWidget_2)
        self.pushButtonProxy_Reset.setEnabled(False)
        self.pushButtonProxy_Reset.setObjectName(_fromUtf8("pushButtonProxy_Reset"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.LabelRole, self.pushButtonProxy_Reset)
        self.pushButtonProxy_Save = QtGui.QPushButton(self.formLayoutWidget_2)
        self.pushButtonProxy_Save.setEnabled(False)
        self.pushButtonProxy_Save.setObjectName(_fromUtf8("pushButtonProxy_Save"))
        self.formLayout_2.setWidget(4, QtGui.QFormLayout.FieldRole, self.pushButtonProxy_Save)
        self.labelProxySetupError = QtGui.QLabel(self.Proxy)
        self.labelProxySetupError.setGeometry(QtCore.QRect(10, 120, 211, 71))
        self.labelProxySetupError.setSizeIncrement(QtCore.QSize(0, 0))
        self.labelProxySetupError.setText(_fromUtf8(""))
        self.labelProxySetupError.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelProxySetupError.setObjectName(_fromUtf8("labelProxySetupError"))
        self.tabWidget.addTab(self.Proxy, _fromUtf8(""))
        self.Port = QtGui.QWidget()
        self.Port.setObjectName(_fromUtf8("Port"))
        self.formLayoutWidget_3 = QtGui.QWidget(self.Port)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(9, 9, 216, 61))
        self.formLayoutWidget_3.setObjectName(_fromUtf8("formLayoutWidget_3"))
        self.formLayout_3 = QtGui.QFormLayout(self.formLayoutWidget_3)
        self.formLayout_3.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_3.setMargin(0)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_6 = QtGui.QLabel(self.formLayoutWidget_3)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_6)
        self.lineEditPort = QtGui.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setKerning(True)
        self.lineEditPort.setFont(font)
        self.lineEditPort.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.lineEditPort.setInputMethodHints(QtCore.Qt.ImhNone)
        self.lineEditPort.setText(_fromUtf8(""))
        self.lineEditPort.setObjectName(_fromUtf8("lineEditPort"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditPort)
        self.pushButtonPort_Default = QtGui.QPushButton(self.formLayoutWidget_3)
        self.pushButtonPort_Default.setObjectName(_fromUtf8("pushButtonPort_Default"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.pushButtonPort_Default)
        self.pushButtonPort_Save = QtGui.QPushButton(self.formLayoutWidget_3)
        self.pushButtonPort_Save.setObjectName(_fromUtf8("pushButtonPort_Save"))
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.FieldRole, self.pushButtonPort_Save)
        self.labelrPortError = QtGui.QLabel(self.Port)
        self.labelrPortError.setGeometry(QtCore.QRect(10, 80, 211, 61))
        self.labelrPortError.setText(_fromUtf8(""))
        self.labelrPortError.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.labelrPortError.setObjectName(_fromUtf8("labelrPortError"))
        self.tabWidget.addTab(self.Port, _fromUtf8(""))
        self.Log = QtGui.QWidget()
        self.Log.setObjectName(_fromUtf8("Log"))
        self.gridLayoutWidget = QtGui.QWidget(self.Log)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(9, 19, 321, 191))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout.addWidget(self.label_8, 0, 2, 1, 1)
        self.spinBox_LogDays = QtGui.QSpinBox(self.gridLayoutWidget)
        self.spinBox_LogDays.setMinimum(5)
        self.spinBox_LogDays.setMaximum(400)
        self.spinBox_LogDays.setProperty("value", 5)
        self.spinBox_LogDays.setObjectName(_fromUtf8("spinBox_LogDays"))
        self.gridLayout.addWidget(self.spinBox_LogDays, 0, 1, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem3, 1, 0, 1, 1)
        self.tabWidget.addTab(self.Log, _fromUtf8(""))

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)
        Dialog.setTabOrder(self.tabWidget, self.lineEditEmail)
        Dialog.setTabOrder(self.lineEditEmail, self.lineEditPassword)
        Dialog.setTabOrder(self.lineEditPassword, self.pushButtonUser_Reset)
        Dialog.setTabOrder(self.pushButtonUser_Reset, self.pushButtonUser_Connect)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(_translate("Dialog", "XCC Automated Settings", None))
        self.label_11.setText(_translate("Dialog", "XCC Service", None))
        self.label_12.setText(_translate("Dialog", "XCC Hot Folder", None))
        self.label_9.setText(_translate("Dialog", "XeikonColorControl", None))
        self.label_15.setText(_translate("Dialog", "XCC Workflow Service", None))
        self.label_13.setText(_translate("Dialog", "XCC Response Service", None))
        self.label_14.setText(_translate("Dialog", "XCC Nearline Spectro", None))
        self.pushButton_Refresh.setText(_translate("Dialog", "Refresh", None))
        self.checkBox_RunBootUp.setText(_translate("Dialog", "Run XCC Agent when the computer starts", None))
        self.label_10.setText(_translate("Dialog", "Version", None))
        self.pushButton_DownloadUpdate.setText(_translate("Dialog", "No updates", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Status), _translate("Dialog", "Status", None))
        self.label.setText(_translate("Dialog", "Email", None))
        self.label_2.setText(_translate("Dialog", "Password", None))
        self.pushButtonUser_Reset.setText(_translate("Dialog", "Reset", None))
        self.pushButtonUser_Connect.setText(_translate("Dialog", "Connect", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.User), _translate("Dialog", "User", None))
        self.label_5.setText(_translate("Dialog", "Proxy", None))
        self.label_3.setText(_translate("Dialog", "Address", None))
        self.label_4.setText(_translate("Dialog", "Port", None))
        self.pushButtonProxy_Reset.setText(_translate("Dialog", "Reset", None))
        self.pushButtonProxy_Save.setText(_translate("Dialog", "Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Proxy), _translate("Dialog", "Proxy", None))
        self.label_6.setText(_translate("Dialog", "Port", None))
        self.pushButtonPort_Default.setText(_translate("Dialog", "Default", None))
        self.pushButtonPort_Save.setText(_translate("Dialog", "Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Port), _translate("Dialog", "Port", None))
        self.label_7.setText(_translate("Dialog", "Log history", None))
        self.label_8.setText(_translate("Dialog", "Days (5-400)", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Log), _translate("Dialog", "Log", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Dialog = QtGui.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

